part of '../../legacy_theme/klp_theme_data.dart';

/// 此分類的預設風格 recipe；schema 的公開 static 成員保留相同值與 const 契約。

const KlpThemeData _defaultColorsLight = KlpThemeData(
	app: KlpPalette.parchment150,
	surface: KlpPalette.parchment100,
	surfaceInset: KlpPalette.parchment100,
	surfaceMuted: KlpPalette.parchment200,
	component: KlpPalette.parchment50,
	stageSurface: KlpPalette.parchment50,
	overlay: KlpPalette.parchment50,
	surfaceRaised: KlpPalette.parchment50,
	modalScrim: KlpPalette.scrim,
	guide: KlpPalette.parchment250,
	divider: KlpPalette.parchment250,
	pagePattern: KlpPalette.parchment250,
	text: KlpPalette.parchment925,
	textMuted: KlpPalette.parchment550,
	textFaint: KlpPalette.parchment550,
	border: KlpPalette.parchment250,
	borderStrong: KlpPalette.parchment250,
	accent: KlpPalette.ink900,
	accentSoft: KlpPalette.ink200,
	interaction: KlpPalette.ink900,
	interactionSoft: KlpPalette.ink200,
	success: KlpPalette.green500,
	warning: KlpPalette.amber500,
	danger: KlpPalette.red300,
	info: KlpPalette.blue500,
	clear: KlpPalette.transparent,
	onLightBackground: KlpPalette.parchment925,
	onDarkBackground: KlpPalette.parchment75,
	mutedOnLightBackground: KlpPalette.parchment550,
	mutedOnDarkBackground: KlpPalette.parchment350,
	faintOnBackground: KlpPalette.parchment550,
);

const KlpThemeData _defaultColorsDark = KlpThemeData(
	app: KlpPalette.parchment950,
	surface: KlpPalette.parchment900,
	surfaceInset: KlpPalette.parchment900,
	surfaceMuted: KlpPalette.parchment750,
	component: KlpPalette.parchment800,
	stageSurface: KlpPalette.parchment800,
	overlay: KlpPalette.parchment800,
	surfaceRaised: KlpPalette.parchment800,
	modalScrim: KlpPalette.scrim,
	guide: KlpPalette.parchment700,
	divider: KlpPalette.parchment700,
	pagePattern: KlpPalette.parchment700,
	text: KlpPalette.parchment75,
	textMuted: KlpPalette.parchment350,
	textFaint: KlpPalette.parchment350,
	border: KlpPalette.parchment700,
	borderStrong: KlpPalette.parchment700,
	accent: KlpPalette.ink50,
	accentSoft: KlpPalette.ink750,
	interaction: KlpPalette.ink50,
	interactionSoft: KlpPalette.ink750,
	success: KlpPalette.green500,
	warning: KlpPalette.amber500,
	danger: KlpPalette.red300,
	info: KlpPalette.blue500,
	clear: KlpPalette.transparent,
	onLightBackground: KlpPalette.parchment925,
	onDarkBackground: KlpPalette.parchment75,
	mutedOnLightBackground: KlpPalette.parchment550,
	mutedOnDarkBackground: KlpPalette.parchment350,
	faintOnBackground: KlpPalette.parchment350,
);

const KlpThemeData _defaultColorsUltraDark = KlpThemeData(
	app: KlpPalette.ink950,
	surface: KlpPalette.ink850,
	surfaceInset: KlpPalette.ink850,
	surfaceMuted: KlpPalette.ink850,
	component: KlpPalette.ink900,
	stageSurface: KlpPalette.ink900,
	overlay: KlpPalette.ink850,
	surfaceRaised: KlpPalette.ink850,
	modalScrim: KlpPalette.scrim,
	guide: KlpPalette.ink450,
	divider: KlpPalette.ink800,
	pagePattern: KlpPalette.ink650,
	text: KlpPalette.ink100,
	textMuted: KlpPalette.ink350,
	textFaint: KlpPalette.ink400,
	border: KlpPalette.line,
	borderStrong: KlpPalette.line,
	accent: KlpPalette.ink100,
	accentSoft: KlpPalette.ink850,
	interaction: KlpPalette.ink100,
	interactionSoft: KlpPalette.ink850,
	success: KlpPalette.green500,
	warning: KlpPalette.amber500,
	danger: KlpPalette.red300,
	info: KlpPalette.blue500,
	clear: KlpPalette.transparent,
);

final KlpThemeData _defaultColorsTransparent = KlpThemeData.dark
		.withWindowTransparency(Brightness.dark);
