import '../klp_typography_theme.dart';
import 'klp_visual_style_json_helpers.dart';
import 'klp_visual_style_json_validation.dart';

const _stringKeys = <String>{
  'sansFamily',
  'sansFallback',
  'monoFamily',
  'monoFallback',
  'uiFamily',
  'bodyFamily',
  'codeFamily',
};
const _numberKeys = <String>{
  'micro',
  'caption',
  'sub',
  'body',
  'lead',
  'h4',
  'h3',
  'h2',
  'h1',
  'display',
  'label',
  'section',
  'headingSmall',
  'heading',
  'title',
  'microLeading',
  'captionLeading',
  'subLeading',
  'bodyLeading',
  'leadLeading',
  'h4Leading',
  'h3Leading',
  'h2Leading',
  'h1Leading',
  'displayLeading',
  'headingLeading',
  'codeLeading',
  'readingLeading',
  'labelLeading',
  'labelTracking',
  'displayTracking',
};
const _weightKeys = <String>{
  'regular',
  'medium',
  'semiBold',
  'bold',
  'extraBold',
  'strong',
};

KlpTypographyTheme decodeTypography(KlpJsonMap json, KlpTypographyTheme base) {
  const path = 'typography';
  rejectUnknown(json, {..._stringKeys, ..._numberKeys, ..._weightKeys}, path);
  double readPositive(String key, double fallback) =>
      readPositiveDouble(json, key, path, fallback);
  return KlpTypographyTheme(
    sansFamily: readString(json, 'sansFamily', path, base.sansFamily),
    sansFallback: readStrings(json, 'sansFallback', path, base.sansFallback),
    monoFamily: readString(json, 'monoFamily', path, base.monoFamily),
    monoFallback: readStrings(json, 'monoFallback', path, base.monoFallback),
    uiFamily: readString(json, 'uiFamily', path, base.uiFamily),
    bodyFamily: readString(json, 'bodyFamily', path, base.bodyFamily),
    codeFamily: readString(json, 'codeFamily', path, base.codeFamily),
    micro: readPositive('micro', base.micro),
    caption: readPositive('caption', base.caption),
    sub: readPositive('sub', base.sub),
    body: readPositive('body', base.body),
    lead: readPositive('lead', base.lead),
    h4: readPositive('h4', base.h4),
    h3: readPositive('h3', base.h3),
    h2: readPositive('h2', base.h2),
    h1: readPositive('h1', base.h1),
    display: readPositive('display', base.display),
    label: readPositive('label', base.label),
    section: readPositive('section', base.section),
    headingSmall: readPositive('headingSmall', base.headingSmall),
    heading: readPositive('heading', base.heading),
    title: readPositive('title', base.title),
    microLeading: readPositive('microLeading', base.microLeading),
    captionLeading: readPositive('captionLeading', base.captionLeading),
    subLeading: readPositive('subLeading', base.subLeading),
    bodyLeading: readPositive('bodyLeading', base.bodyLeading),
    leadLeading: readPositive('leadLeading', base.leadLeading),
    h4Leading: readPositive('h4Leading', base.h4Leading),
    h3Leading: readPositive('h3Leading', base.h3Leading),
    h2Leading: readPositive('h2Leading', base.h2Leading),
    h1Leading: readPositive('h1Leading', base.h1Leading),
    displayLeading: readPositive('displayLeading', base.displayLeading),
    headingLeading: readPositive('headingLeading', base.headingLeading),
    codeLeading: readPositive('codeLeading', base.codeLeading),
    readingLeading: readPositive('readingLeading', base.readingLeading),
    labelLeading: readPositive('labelLeading', base.labelLeading),
    labelTracking: readDouble(json, 'labelTracking', path, base.labelTracking),
    displayTracking: readDouble(
      json,
      'displayTracking',
      path,
      base.displayTracking,
    ),
    regular: readFontWeight(json, 'regular', path, base.regular),
    medium: readFontWeight(json, 'medium', path, base.medium),
    semiBold: readFontWeight(json, 'semiBold', path, base.semiBold),
    bold: readFontWeight(json, 'bold', path, base.bold),
    extraBold: readFontWeight(json, 'extraBold', path, base.extraBold),
    strong: readFontWeight(json, 'strong', path, base.strong),
  );
}

KlpJsonMap encodeTypography(KlpTypographyTheme value) => <String, Object?>{
  'sansFamily': value.sansFamily,
  'sansFallback': value.sansFallback,
  'monoFamily': value.monoFamily,
  'monoFallback': value.monoFallback,
  'uiFamily': value.uiFamily,
  'bodyFamily': value.bodyFamily,
  'codeFamily': value.codeFamily,
  'micro': value.micro,
  'caption': value.caption,
  'sub': value.sub,
  'body': value.body,
  'lead': value.lead,
  'h4': value.h4,
  'h3': value.h3,
  'h2': value.h2,
  'h1': value.h1,
  'display': value.display,
  'label': value.label,
  'section': value.section,
  'headingSmall': value.headingSmall,
  'heading': value.heading,
  'title': value.title,
  'microLeading': value.microLeading,
  'captionLeading': value.captionLeading,
  'subLeading': value.subLeading,
  'bodyLeading': value.bodyLeading,
  'leadLeading': value.leadLeading,
  'h4Leading': value.h4Leading,
  'h3Leading': value.h3Leading,
  'h2Leading': value.h2Leading,
  'h1Leading': value.h1Leading,
  'displayLeading': value.displayLeading,
  'headingLeading': value.headingLeading,
  'codeLeading': value.codeLeading,
  'readingLeading': value.readingLeading,
  'labelLeading': value.labelLeading,
  'labelTracking': value.labelTracking,
  'displayTracking': value.displayTracking,
  'regular': value.regular.value,
  'medium': value.medium.value,
  'semiBold': value.semiBold.value,
  'bold': value.bold.value,
  'extraBold': value.extraBold.value,
  'strong': value.strong.value,
};
