import '../klp_geometry_theme.dart';
import 'klp_visual_style_json_helpers.dart';

KlpJsonMap encodeGeometry(KlpGeometryTheme v) => <String, Object?>{
	'control': <String, Object?>{
		'switchTrackWidth': v.control.switchTrackWidth,
		'switchTrackHeight': v.control.switchTrackHeight,
		'switchThumb': v.control.switchThumb,

		'pageBackgroundHitRadius': v.control.pageBackgroundHitRadius,
		'presenceMarkerExtent': v.control.presenceMarkerExtent,
		'colorPickerCursorRadius': v.control.colorPickerCursorRadius,
		'swatchExtent': v.control.swatchExtent,
		'segmentedProgressHeight': v.control.segmentedProgressHeight,

		'buttonHeightXSmall': v.control.buttonHeightXSmall,
		'buttonHeightSmall': v.control.buttonHeightSmall,
		'buttonHeight': v.control.buttonHeight,
		'buttonHeightLarge': v.control.buttonHeightLarge,
		'buttonHeightXLarge': v.control.buttonHeightXLarge,
		'fieldHeight': v.control.fieldHeight,
		'selectionControl': v.control.selectionControl,
		'selectionIndicatorInset': v.control.selectionIndicatorInset,
		'selectionIcon': v.control.selectionIcon,
		'toggleWidth': v.control.toggleWidth,
		'toggleHeight': v.control.toggleHeight,
		'toggleThumb': v.control.toggleThumb,
		'toggleInset': v.control.toggleInset,
		'segmentedDenseHeight': v.control.segmentedDenseHeight,
		'segmentedDenseInset': v.control.segmentedDenseInset,
		'segmentedDenseContentInset': v.control.segmentedDenseContentInset,
		'segmentedDenseItemHeight': v.control.segmentedDenseItemHeight,
		'slidingSelectionHeight': v.control.slidingSelectionHeight,
		'slidingSelectionSegmentWidth': v.control.slidingSelectionSegmentWidth,
		'slidingSelectionPadding': v.control.slidingSelectionPadding,
		'slidingSelectionIndicatorHeight':
				v.control.slidingSelectionIndicatorHeight,
		'scrollbarThickness': v.control.scrollbarThickness,
		'sliderTrackHeight': v.control.sliderTrackHeight,
		'colorPlaneExtent': v.control.colorPlaneExtent,
		'textFieldIndicatorHeightFactor': v.control.textFieldIndicatorHeightFactor,
		'textFieldLineHeightFactor': v.control.textFieldLineHeightFactor,
		'textFieldMinLines': v.control.textFieldMinLines,
		'textFieldMaxLines': v.control.textFieldMaxLines,
		'fileExplorerRowHeightAdjustment':
				v.control.fileExplorerRowHeightAdjustment,
	},
	'data': <String, Object?>{
		'codeActionButtonSize': v.data.codeActionButtonSize,
		'codeHeaderHeight': v.data.codeHeaderHeight,
		'codeTerminalDot': v.data.codeTerminalDot,
		'codeTerminalDotGap': v.data.codeTerminalDotGap,
		'codeHeaderPaddingX': v.data.codeHeaderPaddingX,
		'codeBodyPaddingX': v.data.codeBodyPaddingX,
		'codeLineNumberWidth': v.data.codeLineNumberWidth,
		'codeWrappedLineWidth': v.data.codeWrappedLineWidth,
		'codeMaximumHeight': v.data.codeMaximumHeight,
		'codeCollapsedHeight': v.data.codeCollapsedHeight,
		'codeDisclosureSize': v.data.codeDisclosureSize,
		'filePreviewHeight': v.data.filePreviewHeight,
		'previewCardCompactHeight': v.data.previewCardCompactHeight,
		'previewCardStandardHeight': v.data.previewCardStandardHeight,
		'previewCardLargeHeight': v.data.previewCardLargeHeight,
		'dateGridCellHeight': v.data.dateGridCellHeight,
		'keyValueLabelWidthCompact': v.data.keyValueLabelWidthCompact,
		'keyValueLabelWidthStandard': v.data.keyValueLabelWidthStandard,
		'stepperMarkerSize': v.data.stepperMarkerSize,
		'stepperLabelWidth': v.data.stepperLabelWidth,
		'progressIndeterminateFraction': v.data.progressIndeterminateFraction,
		'placeholderMinimumHeight': v.data.placeholderMinimumHeight,
		'placeholderContentPaddingY': v.data.placeholderContentPaddingY,
		'placeholderActionPaddingY': v.data.placeholderActionPaddingY,
		'placeholderHatchBand': v.data.placeholderHatchBand,
		'placeholderHatchGap': v.data.placeholderHatchGap,
		'placeholderLabelTracking': v.data.placeholderLabelTracking,
		'placeholderDetailMaximumWidth': v.data.placeholderDetailMaximumWidth,
		'spinnerSquareFactor': v.data.spinnerSquareFactor,
		'spinnerOrbitFactor': v.data.spinnerOrbitFactor,
		'spinnerCornerFactor': v.data.spinnerCornerFactor,
	},
	'layout': <String, Object?>{
		'drawerWidth': v.layout.drawerWidth,
		'drawerHeight': v.layout.drawerHeight,

		'resizeHandleExtent': v.layout.resizeHandleExtent,
		'overlayViewportInset': v.layout.overlayViewportInset,
		'railDropTargetExtent': v.layout.railDropTargetExtent,
		'disclosureIconSize': v.layout.disclosureIconSize,
		'treeLeadingGap': v.layout.treeLeadingGap,
		'tooltipOffsetX': v.layout.tooltipOffsetX,

		'primaryPaneWidth': v.layout.primaryPaneWidth,
		'secondaryPaneWidth': v.layout.secondaryPaneWidth,
		'primaryPaneBreakpoint': v.layout.primaryPaneBreakpoint,
		'primaryPaneContentBreakpoint': v.layout.primaryPaneContentBreakpoint,
		'responsivePaneBreakpoint': v.layout.responsivePaneBreakpoint,
		'secondaryPaneBreakpoint': v.layout.secondaryPaneBreakpoint,
		'menuWidth': v.layout.menuWidth,
		'commandMenuWidth': v.layout.commandMenuWidth,
		'menuHeaderHeight': v.layout.menuHeaderHeight,
		'menuItemHeight': v.layout.menuItemHeight,
		'dialogMaximumWidth': v.layout.dialogMaximumWidth,
		'toastMaximumWidth': v.layout.toastMaximumWidth,
		'inlineNoticeBreakpoint': v.layout.inlineNoticeBreakpoint,
		'statusBarBreakpoint': v.layout.statusBarBreakpoint,
		'settingsDialogMaximumWidth': v.layout.settingsDialogMaximumWidth,
		'settingsDialogMaximumHeight': v.layout.settingsDialogMaximumHeight,
		'settingsPaneGap': v.layout.settingsPaneGap,
		'settingsNavigationWidth': v.layout.settingsNavigationWidth,
		'settingsNavigationMinimumWidth': v.layout.settingsNavigationMinimumWidth,
		'settingsNavigationMaximumWidth': v.layout.settingsNavigationMaximumWidth,
		'settingsContentMaximumWidth': v.layout.settingsContentMaximumWidth,
		'themePreviewTileWidth': v.layout.themePreviewTileWidth,
		'windowHeaderHeight': v.layout.windowHeaderHeight,
		'windowHeaderControlSize': v.layout.windowHeaderControlSize,
		'windowAppIconSize': v.layout.windowAppIconSize,
		'windowIdentityGap': v.layout.windowIdentityGap,
	},
	'optical': <String, Object?>{
		'menuIconOffsetY': v.optical.menuIconOffsetY,
		'railBadgeInset': v.optical.railBadgeInset,
		'statusIconOffsetY': v.optical.statusIconOffsetY,
		'monoBaselineOffsetY': v.optical.monoBaselineOffsetY,
		'uiBaselineOffsetY': v.optical.uiBaselineOffsetY,
	},
};
