const escapeHtml = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

function head(title, prefix) {
	return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Kallopis：-ist 產品家族的 Flutter 宣告式視覺框架。閱讀組裝指南、元件、API 與設計規格。"><title>${escapeHtml(title)} · Kallopis</title><link rel="stylesheet" href="${prefix}assets/site.css"></head>`;
}

function header(prefix, home) {
	return `<a class="skip-link" href="#main-content">跳至主要內容</a><header class="topbar"><a class="brand" href="${prefix}index.html"><span class="brand-mark" aria-hidden="true">K</span>Kallopis</a><nav aria-label="主要導覽"><a href="${prefix}index.html#framework">框架</a><a href="${prefix}docs/index.html" ${home ? '' : 'aria-current="page"'}>文件</a><a href="${prefix}docs/project/CHANGELOG.html">更新紀錄</a></nav><div class="header-actions"><details class="appearance"><summary aria-label="風格設定">風格</summary><div class="appearance-menu"><label>明暗模式<select data-preference="theme"><option value="light">淺色</option><option value="dark">深色</option></select></label><label>框架色調<select data-preference="tone"><option value="warm">暖灰</option><option value="neutral">中性灰</option></select></label><label class="check-label">內容微浮陰影<input type="checkbox" data-preference="lift" checked></label><small>風格 v1.0.0</small></div></details><a class="button primary header-cta" href="${prefix}docs/get-started.html">開始使用 <span aria-hidden="true">↗</span></a></div></header>`;
}

function footer(prefix) {
	return `<footer class="footer"><a class="brand" href="${prefix}index.html">Kallopis</a><span>-ist family · Flutter visual framework</span><a href="https://github.com/miudog/Kallopis">GitHub ↗</a><span>Style 1.0.0</span></footer>`;
}

function scripts(prefix) {
	return `<script src="${prefix}assets/site.js" defer></script></body></html>`;
}

export function shell({title, content, active = '', sourcePath = ''}) {
	const prefix = '../'.repeat(active.split('/').filter(Boolean).length);
	const source = sourcePath ? `<a class="source-link" href="https://github.com/miudog/Kallopis/blob/main/${escapeHtml(sourcePath)}">查看 Markdown 原文 ↗</a>` : '';
	return `${head(title, prefix)}<body data-root="${prefix}" data-page="docs">${header(prefix, false)}<div class="docs-workspace"><aside class="navigator"><details class="doc-navigation" open><summary>文件導覽</summary><div class="nav-content"><label class="search-label" for="search">搜尋文件</label><input id="search" type="search" placeholder="元件、路由、風格…" autocomplete="off"><p id="search-status" role="status" aria-live="polite"></p><nav id="navigation" aria-label="文件目錄"><a href="${prefix}docs/get-started.html">開始使用</a><a href="${prefix}docs/components/index.html">元件</a><a href="${prefix}docs/api/index.html">API</a></nav></div></details></aside><main id="main-content" class="document-frame"><div class="document-bar"><a href="${prefix}docs/index.html">文件</a><span aria-hidden="true">/</span><span>${escapeHtml(title)}</span>${source}</div><article class="prose">${content}</article><div class="document-end"><span>以 Markdown 作為唯一內容來源</span><a href="#main-content">回到頁首 ↑</a></div></main><aside class="toc"><span class="eyebrow">本頁內容</span><nav id="page-toc" aria-label="本頁段落"></nav></aside></div>${footer(prefix)}${scripts(prefix)}`;
}

export function homePage({components = [], apiDocuments = [], guides = []} = {}) {
	return `${head('介面有秩序，內容有空間', '')}<body data-root="" data-page="home">${header('', true)}<main id="main-content" class="home-main">
		<section class="hero"><div class="eyebrow">THE VISUAL LAYER OF THE -IST FAMILY</div><h1>把結構交給框架。<br><span>把注意力留給內容。</span></h1><p class="hero-copy">Kallopis 為 Flutter 提供受控的宣告式組裝、共用元件與一致的風格。<br class="desktop-break">從一棵清楚的節點樹，開始建立你的工作區。</p><div class="hero-actions"><a class="button primary" href="docs/get-started.html">閱讀文件 <span aria-hidden="true">↗</span></a><a class="button secondary" href="docs/components/index.html">探索元件</a></div><p class="release-line">風格 v1.0.0 <span>·</span> 宣告式 API：Experimental</p>
			<div class="workspace-preview" aria-label="Kallopis 工作區結構示意"><div class="preview-heading"><span>Kallopis / Workspace</span><span>DECLARATIVE</span></div><div class="preview-grid"><aside class="preview-sidebar"><span class="eyebrow">PROJECT</span><div class="preview-folder">▾ 工作區</div><a class="preview-item selected" href="docs/guides/ai/composition-templates.html">畫面組裝 <span>01</span></a><a class="preview-item" href="docs/guides/ai/external-components.html">元件定義 <span>02</span></a><a class="preview-item" href="docs/guides/ai/style-v1.html">風格系統 <span>03</span></a><div class="preview-sidebar-end">KlpApplication<br>一個根節點，一條解析路徑。</div></aside><section class="preview-stage"><div class="preview-stage-heading"><span>畫面組裝</span><span>STRUCTURE / STYLE</span></div><div class="preview-content"><article class="paper preview-paper"><span class="paper-meta">WORKSPACE NOTES / 01</span><h2>有秩序，也有溫度。</h2><p>讓框架承接結構，讓內容保留自己的樣子。</p><div class="node-chain"><span>Application</span><span aria-hidden="true">→</span><span>Screen</span><span aria-hidden="true">→</span><span>Frame</span></div></article><div class="preview-memos"><article class="paper memo yellow"><span class="paper-meta">COMPOSITION</span><p>產品提供資料與操作。<br>框架負責視覺與互動。</p></article><article class="paper memo sage"><span class="paper-meta">STYLE 1.0.0</span><p>平整的結構表面。<br>可選的紙片微浮。</p></article></div></div></section></div></div>
		</section>
		<section id="framework" class="feature-section"><div class="feature-copy"><span class="eyebrow">01 / COMPOSE</span><h2>清楚的組裝，<br>從邊界開始。</h2><p>用型別化節點與受限插槽描述畫面。產品提供內容、資料與 callback，Kallopis 接手驗證、狀態安裝與 Flutter 呈現。</p><a class="text-link" href="docs/guides/ai/composition-templates.html">閱讀應用與組裝指南 ↗</a></div><div class="code-paper paper"><div class="code-caption">PUBLIC ENTRY <span>DART</span></div><pre><code><span class="syntax-keyword">import</span> 'package:kallopis/kallopis_declarative.dart';</code></pre><ol class="flow-list"><li><span>01</span><div><strong>KlpApplication</strong><small>唯一的應用組合根</small></div></li><li><span>02</span><div><strong>KlpRouter → KlpScreen</strong><small>以路由對應畫面</small></div></li><li><span>03</span><div><strong>Typed KlpNode tree</strong><small>以資格與插槽建立結構</small></div></li></ol></div></section>
		<section class="feature-section reverse"><div class="style-study"><div class="style-swatches" aria-label="風格表面"><span class="swatch app-swatch">App</span><span class="swatch side-swatch">Sidebar</span><span class="swatch main-swatch">Content</span></div><article class="paper style-note"><span class="paper-meta">MATERIAL / PAPER</span><h3>一套風格，<br>各自負責的表面。</h3><p>結構保持平整，獨立內容才決定是否浮起。</p></article><span class="style-caption">COLOR · PADDING · RADIUS · SHADOW</span></div><div class="feature-copy"><span class="eyebrow">02 / RESOLVE</span><h2>讓風格有來源，<br>讓改動能傳遞。</h2><p>完整原料經過用途語意，解析為元件的呈現資料。暖灰是起點；明暗、色調與內容陰影各有自己的責任。</p><a class="text-link" href="docs/guides/ai/style-v1.html">查看風格 v1.0.0 ↗</a></div></section>
		<section class="documentation-section"><div><span class="eyebrow">03 / UNDERSTAND</span><h2>文件就在下一頁。</h2><p>從第一次組裝，到追查一個元件的來源。</p></div><div class="doc-doors"><a href="docs/get-started.html"><span class="door-number">01</span><h3>開始使用 <span>↗</span></h3><p>入口、約束與組裝方式。</p></a><a href="docs/components/index.html"><span class="door-number">02</span><h3>元件索引 <span>↗</span></h3><p>${components.length} 個現有元件參考頁。</p></a><a href="docs/api/index.html"><span class="door-number">03</span><h3>架構與 API <span>↗</span></h3><p>沿宣告與來源，追查實作。</p></a></div><a class="button primary" href="docs/index.html">進入文件中心 ↗</a></section>
	</main>${footer('')}${scripts('')}`;
}
