import '../klp_typography_theme.dart';
import 'klp_visual_style_json_helpers.dart';

const _stringKeys = <String>{
  'sansFamily',
  'sansFallback',
  'monoFamily',
  'monoFallback',
  'uiFamily',
  'bodyFamily',
  'codeFamily',
};
const _numberKeys = <String>{
  'micro',
  'caption',
  'sub',
  'body',
  'lead',
  'h4',
  'h3',
  'h2',
  'h1',
  'display',
  'label',
  'section',
  'headingSmall',
  'heading',
  'title',
  'microLeading',
  'captionLeading',
  'subLeading',
  'bodyLeading',
  'leadLeading',
  'h4Leading',
  'h3Leading',
  'h2Leading',
  'h1Leading',
  'displayLeading',
  'headingLeading',
  'codeLeading',
  'readingLeading',
  'labelLeading',
  'labelTracking',
  'displayTracking',
};
const _weightKeys = <String>{
  'regular',
  'medium',
  'semiBold',
  'bold',
  'extraBold',
  'strong',
};

KlpTypographyTheme decodeTypography(KlpJsonMap json, KlpTypographyTheme base) {
  const path = 'typography';
  rejectUnknown(json, {..._stringKeys, ..._numberKeys, ..._weightKeys}, path);
  return KlpTypographyTheme(
    sansFamily: readString(json, 'sansFamily', path, base.sansFamily),
    sansFallback: readStrings(json, 'sansFallback', path, base.sansFallback),
    monoFamily: readString(json, 'monoFamily', path, base.monoFamily),
    monoFallback: readStrings(json, 'monoFallback', path, base.monoFallback),
    uiFamily: readString(json, 'uiFamily', path, base.uiFamily),
    bodyFamily: readString(json, 'bodyFamily', path, base.bodyFamily),
    codeFamily: readString(json, 'codeFamily', path, base.codeFamily),
    micro: readDouble(json, 'micro', path, base.micro),
    caption: readDouble(json, 'caption', path, base.caption),
    sub: readDouble(json, 'sub', path, base.sub),
    body: readDouble(json, 'body', path, base.body),
    lead: readDouble(json, 'lead', path, base.lead),
    h4: readDouble(json, 'h4', path, base.h4),
    h3: readDouble(json, 'h3', path, base.h3),
    h2: readDouble(json, 'h2', path, base.h2),
    h1: readDouble(json, 'h1', path, base.h1),
    display: readDouble(json, 'display', path, base.display),
    label: readDouble(json, 'label', path, base.label),
    section: readDouble(json, 'section', path, base.section),
    headingSmall: readDouble(json, 'headingSmall', path, base.headingSmall),
    heading: readDouble(json, 'heading', path, base.heading),
    title: readDouble(json, 'title', path, base.title),
    microLeading: readDouble(json, 'microLeading', path, base.microLeading),
    captionLeading: readDouble(
      json,
      'captionLeading',
      path,
      base.captionLeading,
    ),
    subLeading: readDouble(json, 'subLeading', path, base.subLeading),
    bodyLeading: readDouble(json, 'bodyLeading', path, base.bodyLeading),
    leadLeading: readDouble(json, 'leadLeading', path, base.leadLeading),
    h4Leading: readDouble(json, 'h4Leading', path, base.h4Leading),
    h3Leading: readDouble(json, 'h3Leading', path, base.h3Leading),
    h2Leading: readDouble(json, 'h2Leading', path, base.h2Leading),
    h1Leading: readDouble(json, 'h1Leading', path, base.h1Leading),
    displayLeading: readDouble(
      json,
      'displayLeading',
      path,
      base.displayLeading,
    ),
    headingLeading: readDouble(
      json,
      'headingLeading',
      path,
      base.headingLeading,
    ),
    codeLeading: readDouble(json, 'codeLeading', path, base.codeLeading),
    readingLeading: readDouble(
      json,
      'readingLeading',
      path,
      base.readingLeading,
    ),
    labelLeading: readDouble(json, 'labelLeading', path, base.labelLeading),
    labelTracking: readDouble(json, 'labelTracking', path, base.labelTracking),
    displayTracking: readDouble(
      json,
      'displayTracking',
      path,
      base.displayTracking,
    ),
    regular: readFontWeight(json, 'regular', path, base.regular),
    medium: readFontWeight(json, 'medium', path, base.medium),
    semiBold: readFontWeight(json, 'semiBold', path, base.semiBold),
    bold: readFontWeight(json, 'bold', path, base.bold),
    extraBold: readFontWeight(json, 'extraBold', path, base.extraBold),
    strong: readFontWeight(json, 'strong', path, base.strong),
  );
}

KlpJsonMap encodeTypography(KlpTypographyTheme value) => <String, Object?>{
  'sansFamily': value.sansFamily,
  'sansFallback': value.sansFallback,
  'monoFamily': value.monoFamily,
  'monoFallback': value.monoFallback,
  'uiFamily': value.uiFamily,
  'bodyFamily': value.bodyFamily,
  'codeFamily': value.codeFamily,
  'micro': value.micro,
  'caption': value.caption,
  'sub': value.sub,
  'body': value.body,
  'lead': value.lead,
  'h4': value.h4,
  'h3': value.h3,
  'h2': value.h2,
  'h1': value.h1,
  'display': value.display,
  'label': value.label,
  'section': value.section,
  'headingSmall': value.headingSmall,
  'heading': value.heading,
  'title': value.title,
  'microLeading': value.microLeading,
  'captionLeading': value.captionLeading,
  'subLeading': value.subLeading,
  'bodyLeading': value.bodyLeading,
  'leadLeading': value.leadLeading,
  'h4Leading': value.h4Leading,
  'h3Leading': value.h3Leading,
  'h2Leading': value.h2Leading,
  'h1Leading': value.h1Leading,
  'displayLeading': value.displayLeading,
  'headingLeading': value.headingLeading,
  'codeLeading': value.codeLeading,
  'readingLeading': value.readingLeading,
  'labelLeading': value.labelLeading,
  'labelTracking': value.labelTracking,
  'displayTracking': value.displayTracking,
  'regular': value.regular.value,
  'medium': value.medium.value,
  'semiBold': value.semiBold.value,
  'bold': value.bold.value,
  'extraBold': value.extraBold.value,
  'strong': value.strong.value,
};
