import '../klp_theme.dart';
import 'klp_visual_style_json_helpers.dart';

const _keys = <String>{
  'app',
  'surface',
  'surfaceInset',
  'surfaceMuted',
  'component',
  'stageSurface',
  'overlay',
  'surfaceRaised',
  'modalScrim',
  'guide',
  'divider',
  'text',
  'textMuted',
  'textFaint',
  'border',
  'borderStrong',
  'accent',
  'accentSoft',
  'interaction',
  'interactionSoft',
  'success',
  'warning',
  'danger',
  'info',
  'transparent',
  'onStatus',
  'onLightBackground',
  'onDarkBackground',
  'mutedOnLightBackground',
  'mutedOnDarkBackground',
  'faintOnBackground',
};

KlpThemeData decodeColors(KlpJsonMap json, KlpThemeData base) {
  const path = 'colors';
  rejectUnknown(json, _keys, path);
  return KlpThemeData(
    app: readColor(json, 'app', path, base.app),
    surface: readColor(json, 'surface', path, base.surface),
    surfaceInset: readColor(json, 'surfaceInset', path, base.surfaceInset),
    surfaceMuted: readColor(json, 'surfaceMuted', path, base.surfaceMuted),
    component: readColor(json, 'component', path, base.component),
    stageSurface: readColor(json, 'stageSurface', path, base.stageSurface),
    overlay: readColor(json, 'overlay', path, base.overlay),
    surfaceRaised: readColor(json, 'surfaceRaised', path, base.surfaceRaised),
    modalScrim: readColor(json, 'modalScrim', path, base.modalScrim),
    guide: readColor(json, 'guide', path, base.guide),
    divider: readColor(json, 'divider', path, base.divider),
    text: readColor(json, 'text', path, base.text),
    textMuted: readColor(json, 'textMuted', path, base.textMuted),
    textFaint: readColor(json, 'textFaint', path, base.textFaint),
    border: readColor(json, 'border', path, base.border),
    borderStrong: readColor(json, 'borderStrong', path, base.borderStrong),
    accent: readColor(json, 'accent', path, base.accent),
    accentSoft: readColor(json, 'accentSoft', path, base.accentSoft),
    interaction: readColor(json, 'interaction', path, base.interaction),
    interactionSoft: readColor(
      json,
      'interactionSoft',
      path,
      base.interactionSoft,
    ),
    success: readColor(json, 'success', path, base.success),
    warning: readColor(json, 'warning', path, base.warning),
    danger: readColor(json, 'danger', path, base.danger),
    info: readColor(json, 'info', path, base.info),
    clear: readColor(json, 'transparent', path, base.clear),
    onStatus: readColor(json, 'onStatus', path, base.onStatus),
    onLightBackground: readColor(
      json,
      'onLightBackground',
      path,
      base.onLightBackground,
    ),
    onDarkBackground: readColor(
      json,
      'onDarkBackground',
      path,
      base.onDarkBackground,
    ),
    mutedOnLightBackground: readColor(
      json,
      'mutedOnLightBackground',
      path,
      base.mutedOnLightBackground,
    ),
    mutedOnDarkBackground: readColor(
      json,
      'mutedOnDarkBackground',
      path,
      base.mutedOnDarkBackground,
    ),
    faintOnBackground: readColor(
      json,
      'faintOnBackground',
      path,
      base.faintOnBackground,
    ),
  );
}

KlpJsonMap encodeColors(KlpThemeData value) => <String, Object?>{
  'app': encodeColor(value.app),
  'surface': encodeColor(value.surface),
  'surfaceInset': encodeColor(value.surfaceInset),
  'surfaceMuted': encodeColor(value.surfaceMuted),
  'component': encodeColor(value.component),
  'stageSurface': encodeColor(value.stageSurface),
  'overlay': encodeColor(value.overlay),
  'surfaceRaised': encodeColor(value.surfaceRaised),
  'modalScrim': encodeColor(value.modalScrim),
  'guide': encodeColor(value.guide),
  'divider': encodeColor(value.divider),
  'text': encodeColor(value.text),
  'textMuted': encodeColor(value.textMuted),
  'textFaint': encodeColor(value.textFaint),
  'border': encodeColor(value.border),
  'borderStrong': encodeColor(value.borderStrong),
  'accent': encodeColor(value.accent),
  'accentSoft': encodeColor(value.accentSoft),
  'interaction': encodeColor(value.interaction),
  'interactionSoft': encodeColor(value.interactionSoft),
  'success': encodeColor(value.success),
  'warning': encodeColor(value.warning),
  'danger': encodeColor(value.danger),
  'info': encodeColor(value.info),
  'transparent': encodeColor(value.clear),
  'onStatus': encodeColor(value.onStatus),
  'onLightBackground': encodeColor(value.onLightBackground),
  'onDarkBackground': encodeColor(value.onDarkBackground),
  'mutedOnLightBackground': encodeColor(value.mutedOnLightBackground),
  'mutedOnDarkBackground': encodeColor(value.mutedOnDarkBackground),
  'faintOnBackground': encodeColor(value.faintOnBackground),
};
