import '../klp_geometry_theme.dart';
import 'klp_visual_style_json_helpers.dart';

KlpJsonMap encodeGeometry(KlpGeometryTheme v) => <String, Object?>{
  'control': <String, Object?>{
    'fieldHeight': v.control.fieldHeight,
    'selectionControl': v.control.selectionControl,
    'selectionIndicatorInset': v.control.selectionIndicatorInset,
    'selectionIcon': v.control.selectionIcon,
    'toggleWidth': v.control.toggleWidth,
    'toggleHeight': v.control.toggleHeight,
    'toggleThumb': v.control.toggleThumb,
    'toggleInset': v.control.toggleInset,
    'segmentedDenseHeight': v.control.segmentedDenseHeight,
    'segmentedDenseInset': v.control.segmentedDenseInset,
    'segmentedDenseItemHeight': v.control.segmentedDenseItemHeight,
    'scrollbarThickness': v.control.scrollbarThickness,
    'sliderTrackHeight': v.control.sliderTrackHeight,
    'textFieldIndicatorHeightFactor': v.control.textFieldIndicatorHeightFactor,
    'textFieldLineHeightFactor': v.control.textFieldLineHeightFactor,
    'textFieldMinLines': v.control.textFieldMinLines,
    'textFieldMaxLines': v.control.textFieldMaxLines,
    'fileExplorerRowHeightAdjustment':
        v.control.fileExplorerRowHeightAdjustment,
  },
  'data': <String, Object?>{
    'codeActionButtonSize': v.data.codeActionButtonSize,
    'codeHeaderHeight': v.data.codeHeaderHeight,
    'codeTerminalDot': v.data.codeTerminalDot,
    'codeTerminalDotGap': v.data.codeTerminalDotGap,
    'codeHeaderPaddingX': v.data.codeHeaderPaddingX,
    'codeBodyPaddingX': v.data.codeBodyPaddingX,
    'codeLineNumberWidth': v.data.codeLineNumberWidth,
    'codeWrappedLineWidth': v.data.codeWrappedLineWidth,
    'codeMaximumHeight': v.data.codeMaximumHeight,
    'codeCollapsedHeight': v.data.codeCollapsedHeight,
    'codeDisclosureSize': v.data.codeDisclosureSize,
    'placeholderMinimumHeight': v.data.placeholderMinimumHeight,
    'placeholderContentPaddingY': v.data.placeholderContentPaddingY,
    'placeholderActionPaddingY': v.data.placeholderActionPaddingY,
    'placeholderHatchBand': v.data.placeholderHatchBand,
    'placeholderHatchGap': v.data.placeholderHatchGap,
    'placeholderLabelTracking': v.data.placeholderLabelTracking,
    'placeholderDetailMaximumWidth': v.data.placeholderDetailMaximumWidth,
    'spinnerSquareFactor': v.data.spinnerSquareFactor,
    'spinnerOrbitFactor': v.data.spinnerOrbitFactor,
    'spinnerCornerFactor': v.data.spinnerCornerFactor,
  },
  'layout': <String, Object?>{
    'primaryPaneWidth': v.layout.primaryPaneWidth,
    'secondaryPaneWidth': v.layout.secondaryPaneWidth,
    'primaryPaneBreakpoint': v.layout.primaryPaneBreakpoint,
    'primaryPaneContentBreakpoint': v.layout.primaryPaneContentBreakpoint,
    'secondaryPaneBreakpoint': v.layout.secondaryPaneBreakpoint,
    'menuWidth': v.layout.menuWidth,
    'menuHeaderHeight': v.layout.menuHeaderHeight,
    'menuItemHeight': v.layout.menuItemHeight,
    'dialogMaximumWidth': v.layout.dialogMaximumWidth,
    'toastMaximumWidth': v.layout.toastMaximumWidth,
    'inlineNoticeBreakpoint': v.layout.inlineNoticeBreakpoint,
    'statusBarBreakpoint': v.layout.statusBarBreakpoint,
    'settingsContentMaximumWidth': v.layout.settingsContentMaximumWidth,
    'themePreviewTileWidth': v.layout.themePreviewTileWidth,
    'windowAppIconSize': v.layout.windowAppIconSize,
    'windowIdentityGap': v.layout.windowIdentityGap,
  },
  'optical': <String, Object?>{
    'menuIconOffsetY': v.optical.menuIconOffsetY,
    'railBadgeInset': v.optical.railBadgeInset,
    'statusIconOffsetY': v.optical.statusIconOffsetY,
    'monoBaselineOffsetY': v.optical.monoBaselineOffsetY,
    'uiBaselineOffsetY': v.optical.uiBaselineOffsetY,
  },
};
