import '../klp_spacing_theme.dart';
import 'klp_visual_style_json_helpers.dart';
import 'klp_visual_style_json_validation.dart';

const _keys = <String>{
	'space0_5',
	'space1',
	'space2',
	'space3',
	'space4',
	'space6',
	'space8',
	'space12',
	'space16',
	'space24',
	'hairline',
	'tight',
	'contentInlineGap',
	'contentStackGap',
	'contentInset',
	'controlContentGap',
	'controlInset',
	'actionGap',
	'chromeGap',
	'chromePanelInset',
	'chromeToolbarGap',
	'navigationItemInset',
	'navigationRailInset',
	'navigationRailItemGap',
	'overlayContentInset',
	'overlayHeadingGap',
	'overlayItemGap',
	'navigationSectionGap',
	'appFrameInset',
	'workbenchContentInset',
	'windowHeaderMargin',
	'dockMargin',
	'base',
	'comfortable',
	'loose',
	'section',
	'sectionLarge',
	'page',
	'pageLarge',
	'controlPaddingXSmall',
	'controlPaddingX',
	'controlPaddingXLarge',
	'controlPaddingXXLarge',
	'controlPaddingY',
	'containerPadding',
	'itemGap',
	'groupGap',
	'controlHeightXSmall',
	'controlHeightSmall',
	'controlHeight',
	'controlHeightLarge',
	'controlHeightXLarge',
	'iconSmall',
	'iconBase',
	'iconGlyph',
	'icon',
	'iconMedium',
	'iconLarge',
	'chromeHeader',
	'chromeStatusBar',
	'chromeRail',
	'chromeTab',
	'iconButton',
	'iconTiny',
	'indicatorDot',
	'indicatorDotLarge',
	'noticeIconSlot',
	'toastIconSlot',
	'gutterNumber',
	'gutterMarker',
	'micro',
	'calendarContentCell',
	'gridTileWidth',
	'iconMicro',
	'avatarSmall',
	'progressTrack',
	'skeletonLine',
	'railItem',
};

KlpSpacingTheme decodeSpacing(KlpJsonMap json, KlpSpacingTheme base) {
	const path = 'spacing';
	rejectUnknown(json, _keys, path);
	double read(String key, double fallback) =>
			readNonNegativeDouble(json, key, path, fallback);
	return base.copyWith(
		space0_5: read('space0_5', base.space0_5),
		space1: read('space1', base.space1),
		space2: read('space2', base.space2),
		space3: read('space3', base.space3),
		space4: read('space4', base.space4),
		space6: read('space6', base.space6),
		space8: read('space8', base.space8),
		space12: read('space12', base.space12),
		space16: read('space16', base.space16),
		space24: read('space24', base.space24),
		hairline: read('hairline', base.hairline),
		tight: read('tight', base.tight),
		contentInlineGap: read('contentInlineGap', base.contentInlineGap),
		contentStackGap: read('contentStackGap', base.contentStackGap),
		contentInset: read('contentInset', base.contentInset),
		controlContentGap: read('controlContentGap', base.controlContentGap),
		controlInset: read('controlInset', base.controlInset),
		actionGap: read('actionGap', base.actionGap),
		chromeGap: read('chromeGap', base.chromeGap),
		chromePanelInset: read('chromePanelInset', base.chromePanelInset),
		chromeToolbarGap: read('chromeToolbarGap', base.chromeToolbarGap),
		navigationItemInset: read('navigationItemInset', base.navigationItemInset),
		navigationRailInset: read('navigationRailInset', base.navigationRailInset),
		navigationRailItemGap: read('navigationRailItemGap', base.navigationRailItemGap),
		overlayContentInset: read('overlayContentInset', base.overlayContentInset),
		overlayHeadingGap: read('overlayHeadingGap', base.overlayHeadingGap),
		overlayItemGap: read('overlayItemGap', base.overlayItemGap),
		navigationSectionGap: read('navigationSectionGap', base.navigationSectionGap),
		appFrameInset: read('appFrameInset', base.appFrameInset),
		workbenchContentInset: read('workbenchContentInset', base.workbenchContentInset),
		windowHeaderMargin: read('windowHeaderMargin', base.windowHeaderMargin),
		dockMargin: read('dockMargin', base.dockMargin),
		base: read('base', base.base),
		comfortable: read('comfortable', base.comfortable),
		loose: read('loose', base.loose),
		section: read('section', base.section),
		sectionLarge: read('sectionLarge', base.sectionLarge),
		page: read('page', base.page),
		pageLarge: read('pageLarge', base.pageLarge),
		controlPaddingXSmall: read(
			'controlPaddingXSmall',
			base.controlPaddingXSmall,
		),
		controlPaddingX: read('controlPaddingX', base.controlPaddingX),
		controlPaddingXLarge: read(
			'controlPaddingXLarge',
			base.controlPaddingXLarge,
		),
		controlPaddingXXLarge: read(
			'controlPaddingXXLarge',
			base.controlPaddingXXLarge,
		),
		controlPaddingY: read('controlPaddingY', base.controlPaddingY),
		containerPadding: read('containerPadding', base.containerPadding),
		itemGap: read('itemGap', base.itemGap),
		groupGap: read('groupGap', base.groupGap),
		controlHeightXSmall: read('controlHeightXSmall', base.controlHeightXSmall),
		controlHeightSmall: read('controlHeightSmall', base.controlHeightSmall),
		controlHeight: read('controlHeight', base.controlHeight),
		controlHeightLarge: read('controlHeightLarge', base.controlHeightLarge),
		controlHeightXLarge: read('controlHeightXLarge', base.controlHeightXLarge),
		iconSmall: read('iconSmall', base.iconSmall),
		iconBase: read('iconBase', base.iconBase),
		iconGlyph: read('iconGlyph', base.iconGlyph),
		icon: read('icon', base.icon),
		iconMedium: read('iconMedium', base.iconMedium),
		iconLarge: read('iconLarge', base.iconLarge),
		chromeHeader: read('chromeHeader', base.chromeHeader),
		chromeStatusBar: read('chromeStatusBar', base.chromeStatusBar),
		chromeRail: read('chromeRail', base.chromeRail),
		chromeTab: read('chromeTab', base.chromeTab),
		iconButton: read('iconButton', base.iconButton),
		iconTiny: read('iconTiny', base.iconTiny),
		indicatorDot: read('indicatorDot', base.indicatorDot),
		indicatorDotLarge: read('indicatorDotLarge', base.indicatorDotLarge),
		noticeIconSlot: read('noticeIconSlot', base.noticeIconSlot),
		toastIconSlot: read('toastIconSlot', base.toastIconSlot),
		gutterNumber: read('gutterNumber', base.gutterNumber),
		gutterMarker: read('gutterMarker', base.gutterMarker),
		micro: read('micro', base.micro),
		calendarContentCell: read('calendarContentCell', base.calendarContentCell),
		gridTileWidth: read('gridTileWidth', base.gridTileWidth),
		iconMicro: read('iconMicro', base.iconMicro),
		avatarSmall: read('avatarSmall', base.avatarSmall),
		progressTrack: read('progressTrack', base.progressTrack),
		skeletonLine: read('skeletonLine', base.skeletonLine),
		railItem: read('railItem', base.railItem),
	);
}
