part of '../theme/klp_theme_data.dart';

/// 此分類的預設風格 recipe；schema 的公開 static 成員保留相同值與 const 契約。

const KlpThemeData _defaultColorsLight = KlpThemeData(
	app: KlpPalette.ink150,
	surface: KlpPalette.ink100,
	surfaceInset: KlpPalette.ink100,
	surfaceMuted: KlpPalette.ink100,
	component: KlpPalette.ink50,
	stageSurface: KlpPalette.ink50,
	overlay: KlpPalette.ink50,
	surfaceRaised: KlpPalette.ink50,
	modalScrim: KlpPalette.scrim,
	guide: KlpPalette.ink400,
	divider: KlpPalette.ink100,
	pagePattern: KlpPalette.ink200,
	text: KlpPalette.ink900,
	textMuted: KlpPalette.ink550,
	textFaint: KlpPalette.ink400,
	border: KlpPalette.line,
	borderStrong: KlpPalette.line,
	accent: KlpPalette.ink900,
	accentSoft: KlpPalette.ink200,
	interaction: KlpPalette.ink900,
	interactionSoft: KlpPalette.ink200,
	success: KlpPalette.green500,
	warning: KlpPalette.amber500,
	danger: KlpPalette.red300,
	info: KlpPalette.blue500,
	clear: KlpPalette.transparent,
);

const KlpThemeData _defaultColorsDark = KlpThemeData(
	app: KlpPalette.ink850,
	surface: KlpPalette.ink750,
	surfaceInset: KlpPalette.ink750,
	surfaceMuted: KlpPalette.ink750,
	component: KlpPalette.ink800,
	stageSurface: KlpPalette.ink800,
	overlay: KlpPalette.ink750,
	surfaceRaised: KlpPalette.ink750,
	modalScrim: KlpPalette.scrim,
	guide: KlpPalette.ink400,
	divider: KlpPalette.ink750,
	pagePattern: KlpPalette.ink600,
	text: KlpPalette.ink50,
	textMuted: KlpPalette.ink300,
	textFaint: KlpPalette.ink400,
	border: KlpPalette.line,
	borderStrong: KlpPalette.line,
	accent: KlpPalette.ink50,
	accentSoft: KlpPalette.ink750,
	interaction: KlpPalette.ink50,
	interactionSoft: KlpPalette.ink750,
	success: KlpPalette.green500,
	warning: KlpPalette.amber500,
	danger: KlpPalette.red300,
	info: KlpPalette.blue500,
	clear: KlpPalette.transparent,
);

const KlpThemeData _defaultColorsUltraDark = KlpThemeData(
	app: KlpPalette.ink950,
	surface: KlpPalette.ink850,
	surfaceInset: KlpPalette.ink850,
	surfaceMuted: KlpPalette.ink850,
	component: KlpPalette.ink900,
	stageSurface: KlpPalette.ink900,
	overlay: KlpPalette.ink850,
	surfaceRaised: KlpPalette.ink850,
	modalScrim: KlpPalette.scrim,
	guide: KlpPalette.ink450,
	divider: KlpPalette.ink800,
	pagePattern: KlpPalette.ink650,
	text: KlpPalette.ink100,
	textMuted: KlpPalette.ink350,
	textFaint: KlpPalette.ink400,
	border: KlpPalette.line,
	borderStrong: KlpPalette.line,
	accent: KlpPalette.ink100,
	accentSoft: KlpPalette.ink850,
	interaction: KlpPalette.ink100,
	interactionSoft: KlpPalette.ink850,
	success: KlpPalette.green500,
	warning: KlpPalette.amber500,
	danger: KlpPalette.red300,
	info: KlpPalette.blue500,
	clear: KlpPalette.transparent,
);

final KlpThemeData _defaultColorsTransparent = KlpThemeData.dark
		.withWindowTransparency(Brightness.dark);
